### ISSUE TITLE
Redis client for ReactNative

### ISSUE THREAD

**Issue by johnbwilliams** [sklivvz/cthulhu#4]
Hi sklivvz,

Can cthulhu be used to create Redis client for ReactNative?

Are you interested in developing a Redis client for ReactNative for a fee?

Or, could you refer me to anyone who might be interested?

Thank you!
John Williams

**Comment by sklivvz** [comment]
Hi, sorry about the delay but I had stopped my notifications. No -- Chthulu works under the hood, and any Redis client will still see the same interface to Redis.
